policy:
  model_name: HuggingFaceTB/SmolVLM2-500M-Video-Instruct
  load_vlm_weights: true
  freeze_vision_encoder: true
  attention_mode: cross_attn
  num_expert_layers: -1
  num_vlm_layers: 16
  self_attn_every_n_layers: 2
  expert_width_multiplier: 0.75
  add_image_special_tokens: false
  tokenizer_max_length: 48
  pad_language_to: longest
  max_state_dim: 32
  prefix_length: -1
  use_gpu_preprocessing: true
  image_size: [512, 512]
  camera_keys: null
  empty_cameras: 0

flow:
  max_action_dim: 32
  chunk_size: 50
  flow_hidden_dim: 1024
  flow_steps: 10
  min_period: 4.0e-3
  max_period: 4.0
  time_beta_alpha: 1.5
  time_beta_beta: 1.0

latent:
  latent_vector_dim: 32
